### PR TITLE
Update SparkPostMessage to support campaign

### LINKED ISSUE #136: Django: unable to set campaign when using EmailMessage object
I'm trying to send an email with a campaign id using a `EmailMessage` object as follows:

```
msg = EmailMessage(
    subject='Test Campaign',
    to=['test@test.com']
)
msg.template = 'test-template'
msg.substitution_data = substitution_data
msg.campaign = 'test-campaign'
msg.send()
```

Viewing the message in the SparkPost Dashboard, I can see the template and data are set, but the campaign remains empty. Following https://github.com/SparkPost/python-sparkpost/issues/107, it looks like the problem is in the `SparkPostMessage` class. `substitution_data`, `template` are copied there, but not `campaign`.

### PR DESCRIPTION
**Pull request by andyzickler**
Updates sending a Django `EmailMessage` to support a `campaign` attribute. Also adds a test to verify.

Closes #136

### CODE REVIEW

**Comment by richleland** [comment]
Thanks for the contribution @andyzickler!

This highlights a design flaw in 1.0 that we're looking to address in 2.0 - passing through params to the API so we don't have to make library updates for something so basic as this. It's also worth noting that in 2.0 we're considering removing the Django backend in favor of [django-anymail](https://github.com/anymail/django-anymail).

**Comment by andyzickler** [comment]
Glad I was able to help out. I did see your comments in https://github.com/SparkPost/python-sparkpost/issues/110 but I figured because I had already fixed it locally that I would just go ahead an submit the patch. Thanks for the heads up about django-anymail.

**Comment by clhamilton** [comment]
Any chance this PR will be released soon?

**Comment by richleland** [comment]
@clhamilton @andyzickler yeah we can cut a release tomorrow. I'll update the ticket as soon as it's ready.

**Comment by richleland** [comment]
[1.3.4](https://github.com/SparkPost/python-sparkpost/releases/tag/v1.3.4) is now up on PyPI.

**Comment by andyzickler** [comment]
Thank you so much!

**Pull request merged**
