### PR TITLE
Issue #107 -Django backend unable to use templates, substitution_data

### PR DESCRIPTION
**Pull request by pl-jankowskimichal**
changed SparkPostMessage class __init__ method so those parameters will be accepted now.

### CODE REVIEW

**Comment by richleland** [comment]
Great PR - thanks for the contribution. I'm going to go ahead and merge this. I do think we might need something more holistic so we don't need to keep adding code for every possible param, but I'll create an issue and work on that separately.

**Comment by lee-kagiso** [comment]
When are we going to make this release?

**Comment by richleland** [comment]
I'll be cutting a release today for this and #100.

**Comment by richleland** [comment]
And by today I mean a minute ago @lee-kagiso. 1.2.0 has been published.

**Comment by lee-kagiso** [comment]
Thanks!

**Pull request merged**
