### PR TITLE
fix: recipient emails can be provided as unicode strings

### PR DESCRIPTION
**Pull request by puttu**

### CODE REVIEW

**Comment by richleland** [comment]
Thanks for the PR @puttu ! This lib needs to be compatible with python 2 and 3 so you'll have to add some extra logic to deal with the fact that `basestring` doesn't exist in py3 - check out this stackoverflow question:

http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

**Comment by puttu** [comment]
Good catch! Fixed.

**Comment by richleland** [comment]
Awesome - mind adding a test using a unicode recipient?

**Comment by puttu** [comment]
Hehe, and here I thought I'd sneak in a 10-character fix. :)

**Comment by richleland** [comment]
Thanks for the contribution @puttu!

**Comment by jsuter** [comment]
Thanks for the fix @puttu!

**Pull request merged**
